### ISSUE TITLE
Add `Spotter`, `Pot`, `Jug` to starknet-dss

### ISSUE THREAD

**Issue by maciejka** [makerdao/starknet-dss#37]

**Comment by EvolveArt** [comment]
Timestamp manipulation issue encountered.

[This](https://github.com/makerdao/xdomain-dss/blob/add-end/src/Pot.sol#L129) assertion will fail at every test as every invoke triggers a new block creation.

**Comment by EvolveArt** [comment]
https://github.com/Shard-Labs/starknet-devnet/issues/361
